### ISSUE TITLE
Error when opening app with add-on enabled

### ISSUE THREAD

**Issue by cati-chatou** [dayjaby/yomisama#10]
I installed app, restarted Anki. Got the below error. I closed and tried to configure it but I don't really understand how to configure it so I could achieve my goals. Can you help with the error and maybe you have some configuration instruction (what is what)?

Debug info:

Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.9.7 PyQt 5.13.2
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-23 12:44:18
Add-ons possibly involved: ⁨Yomisama JapaneseChinese⁩

Traceback (most recent call last):
  File "aqt/main.py", line 497, in loadCollection
  File "aqt/main.py", line 631, in moveToState
  File "aqt/gui_hooks.py", line 1922, in __call__
  File "anki/hooks.py", line 583, in runHook
  File "/Users/cati/Library/Application Support/Anki2/addons21/907186589/yomi_base/anki_bridge.py", line 367, in onBeforeStateChange
    aqt.mw.col.decks = DeckManager(aqt.mw.col,yomichanInstance.getFileCache())
  File "/Users/cati/Library/Application Support/Anki2/addons21/907186589/yomi_base/deckManager.py", line 18, in __init__
    self.dconf = col.decks.dconf
AttributeError: 'DeckManager' object has no attribute 'dconf'`

**Comment by dayjaby** [comment]
When did you install the plugin? I updated it 11 days ago and this error should be fixed.

The default configuration is quite good already. You only need to change the configs if you want to change note type, specify which data goes into which note field, the target deck etc.

**Comment by cati-chatou** [comment]
Installed it just today.

**Comment by dayjaby** [comment]
Latest Anki / latest Yomisama should resolve this issue.
