### ISSUE TITLE
Errors when trying to open text

### ISSUE THREAD

**Issue by natanfudge** [dayjaby/yomisama#11]
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.28 (7d8818f8) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-24 10:27:43

Caught exception:
Traceback (most recent call last):
  File "C:\Users\natan\AppData\Roaming\Anki2\addons21\907186589\yomi_base\reader.py", line 273, in onActionOpen
    self.openFile(filename)
  File "C:\Users\natan\AppData\Roaming\Anki2\addons21\907186589\yomi_base\reader.py", line 425, in openFile
    self.currentFile = FileState(filename, self.preferences['stripReadings'],self.languages,self.profiles)
  File "C:\Users\natan\AppData\Roaming\Anki2\addons21\907186589\yomi_base\file_state.py", line 42, in __init__
    self.load()
  File "C:\Users\natan\AppData\Roaming\Anki2\addons21\907186589\yomi_base\file_state.py", line 52, in load
    self.content = fp.read()
  File "C:\python38\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 14: character maps to <undefined>

```
This is the text I used: 
[crashy crash.txt](https://github.com/dayjaby/yomisama/files/5118926/crashy.crash.txt)

**Comment by dayjaby** [comment]
Codec problems shouldn't be a problem with the newest Anki/Yomisama version anymore.
